version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mindfactory
      POSTGRES_PASSWORD: mindhash1234
      POSTGRES_DB: newsdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build: ./mindfactory-news-api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://mindfactory:mindhash1234@db:5432/newsdb?schema=public
    command: npx prisma migrate deploy

  seed:
    build: ./mindfactory-news-api
    depends_on:
      - migrate
    environment:
      - DATABASE_URL=postgresql://mindfactory:mindhash1234@db:5432/newsdb?schema=public
    command: npx prisma db seed

  backend:
    build: ./mindfactory-news-api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://mindfactory:mindhash1234@db:5432/newsdb?schema=public
      - NODE_ENV=production
    depends_on:
      - seed
    command: node dist/index.js

  frontend:
    build: ./mindfactory-news-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  pgdata: