version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: news-postgres
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: mindfactory
      POSTGRES_PASSWORD: mindhash1234
      POSTGRES_DB: newsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: